server:
  port: 8088
  servlet:
    contextPath: /api
spring:
  application:
    name: cardservice

  jpa:
    hibernate:
#        ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/card_db?useSSL=false&allowPublicKeyRetrieval=true
    username: techcamp2
    password: password

  #  customerService:
  #    host: http://localhost:8082/api/customer
  #    endpoint:
  #      getInfo: info

  cardService:
    host: http://localhost:8082/api/card
    endpoint:
      getInfo: info

#  userService:
#    host: http://192.168.111.20:8889/api/user
#    endpoint:
#      getInfo: info

#restTemplate:
#  connectionTimeOut: 5000
#  readTimeOut: 10000